# Generated by Django 4.0.3 on 2022-10-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceApiFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_api', models.CharField(choices=[('coingecko', 'coingecko.com'), ('coinmarketcap', 'coinmarketcap.com')], max_length=50)),
                ('error', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price API Failure',
                'verbose_name_plural': 'Price API Failures',
            },
        ),
    ]
