# Generated by Django 4.0.3 on 2022-10-05 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=255, unique=True)),
                ('mpk', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceApiFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_api', models.CharField(choices=[('coingecko', 'coingecko.com'), ('coinmarketcap', 'coinmarketcap.com')], max_length=50)),
                ('error', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price API Failure',
                'verbose_name_plural': 'Price API Failures',
            },
        ),
        migrations.CreateModel(
            name='CryptoAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('btc_due', models.DecimalField(decimal_places=7, max_digits=10)),
                ('cad_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('btc_paid', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('wallet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.cryptowallet')),
            ],
        ),
    ]
