# Generated by Django 4.0.3 on 2022-10-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_cryptowallet_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoaddress',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
