# Generated by Django 4.0.3 on 2022-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_cryptowalletmanager_remove_cryptowallet_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoWalletManager',
        ),
        migrations.RemoveField(
            model_name='cryptowallet',
            name='wallet_path',
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='slug',
            field=models.SlugField(default='asdf', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
