# Generated by Django 4.0.3 on 2022-10-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_delete_cryptowalletmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
