# Generated by Django 4.0.3 on 2022-10-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_remove_cryptowallet_vendor_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoaddress',
            name='is_used',
        ),
    ]
