# Generated by Django 4.0.3 on 2022-10-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_payment_ccy_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ccy_error',
            new_name='problem',
        ),
    ]
