# Generated by Django 4.0.3 on 2022-10-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_remove_payment_price_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletApiFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet API Failure',
                'verbose_name_plural': 'Wallet API Failures',
            },
        ),
    ]
