# Generated by Django 4.0.3 on 2022-10-21 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_priceapifailure_notes'),
        ('wallet', '0027_walletapifailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='coin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='price.cryptocoin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletapifailure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
