# Generated by Django 4.0.3 on 2022-10-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0028_cryptowallet_coin_id_walletapifailure_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_problem',
        ),
    ]
