# Generated by Django 4.0.3 on 2022-10-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0030_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.paymentrequest'),
        ),
    ]
