# Generated by Django 4.0.3 on 2022-10-24 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0031_payment_pay_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_unconfirmed', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('btc_confirmed', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.cryptoaddress')),
            ],
        ),
    ]
