# Generated by Django 4.0.3 on 2022-10-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0032_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressNotification',
        ),
    ]
