# Generated by Django 4.0.3 on 2022-10-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0033_delete_addressnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletapifailure',
            old_name='notes',
            new_name='details',
        ),
        migrations.AddField(
            model_name='balance',
            name='status',
            field=models.CharField(default='abcdefg1234567', max_length=255),
            preserve_default=False,
        ),
    ]
