# Generated by Django 4.0.3 on 2022-10-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0034_rename_notes_walletapifailure_details_balance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
