# Generated by Django 4.0.3 on 2022-10-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0035_remove_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('underpaid', 'Underpaid'), ('overpaid', 'Overpaid'), ('orphan_payment', 'OrphanPaymentError')], default='paid', max_length=255),
            preserve_default=False,
        ),
    ]
