# Generated by Django 4.0.3 on 2022-10-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0037_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='status',
            new_name='txid',
        ),
    ]
