# Generated by Django 4.0.3 on 2022-10-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0038_rename_status_balance_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='vendor_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
