# Generated by Django 4.0.3 on 2022-11-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0039_alter_cryptowallet_vendor_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptowallet',
            old_name='vendor_url',
            new_name='notify_url',
        ),
    ]
