# Generated by Django 4.0.3 on 2022-11-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_delete_vendorpayment'),
        ('wallet', '0041_cryptowallet_wallet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='plan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.plan'),
        ),
    ]
