# Generated by Django 4.0.3 on 2022-10-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_priceapifailure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceapifailure',
            name='failed_api',
        ),
        migrations.AlterField(
            model_name='priceapifailure',
            name='error',
            field=models.CharField(max_length=255),
        ),
    ]
