# Generated by Django 4.0.3 on 2022-10-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_remove_priceapifailure_failed_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceapifailure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
