# Generated by Django 4.0.3 on 2022-11-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottlePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burst', models.CharField(max_length=255)),
                ('sustained', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='VendorPayment',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='throttle_rate',
            new_name='usage_rate',
        ),
    ]
