# Generated by Django 4.0.3 on 2022-11-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_throttleplan_delete_vendorpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_btc', models.DecimalField(decimal_places=7, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
