# Generated by Django 4.0.3 on 2022-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_planpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(default='bleh', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
