# Generated by Django 4.0.3 on 2022-11-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_plan_plan_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanPayment',
        ),
    ]
