# Generated by Django 4.0.3 on 2022-11-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0041_cryptowallet_wallet_code'),
        ('plan', '0005_delete_planpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_btc', models.DecimalField(decimal_places=7, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.cryptowallet')),
            ],
        ),
    ]
