# Generated by Django 4.0.3 on 2022-11-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_vendorpayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThrottlePlan',
            new_name='ThrottleRate',
        ),
    ]
