# Generated by Django 4.0.3 on 2022-11-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_plan_throttle_id_vendorpayment_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorPayment',
        ),
    ]
