# Generated by Django 4.0.3 on 2022-10-06 07:56

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_cryptowallet_vendor_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='mpk',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, unique=True)),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='vendor_key',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, unique=True)),
        ),
    ]
