# Generated by Django 4.0.3 on 2022-10-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_cryptowallet_mpk_alter_cryptowallet_vendor_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWalletManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cryptowallet',
            name='slug',
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='wallet_path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
