# Generated by Django 4.0.3 on 2022-10-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_cryptowallet_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoaddress',
            name='is_used',
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_due', models.DecimalField(decimal_places=7, max_digits=10)),
                ('cad_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.cryptoaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_paid', models.DecimalField(decimal_places=7, max_digits=10)),
                ('cad_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('address_oto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.cryptoaddress')),
            ],
        ),
    ]
