# Generated by Django 4.0.3 on 2022-10-11 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_remove_cryptoaddress_is_used_paymentrequest_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='btc_paid',
            new_name='btc_confirmed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='address_oto',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cad_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='address_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wallet.cryptoaddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='btc_unconfirmed',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='cad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
