# Generated by Django 4.0.3 on 2022-10-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_rename_btc_paid_payment_btc_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='btc_confirmed',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='btc_unconfirmed',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
