# Generated by Django 4.0.3 on 2022-10-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_addressnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cad',
            new_name='cad_exchange',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='btc_unconfirmed',
        ),
    ]
