# Generated by Django 4.0.3 on 2022-10-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_rename_cad_payment_cad_exchange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoaddress',
            name='btc_due',
        ),
        migrations.RemoveField(
            model_name='cryptoaddress',
            name='btc_paid',
        ),
        migrations.RemoveField(
            model_name='cryptoaddress',
            name='cad_due',
        ),
        migrations.RemoveField(
            model_name='cryptoaddress',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='cryptoaddress',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
