# Generated by Django 4.0.3 on 2022-10-14 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_remove_cryptoaddress_btc_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptowallet',
            name='vendor_key',
        ),
    ]
