# Generated by Django 4.0.3 on 2022-10-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_remove_cryptoaddress_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ccy_error',
            field=models.BooleanField(default=False),
        ),
    ]
