# Generated by Django 4.0.3 on 2022-10-16 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_priceapifailure'),
        ('wallet', '0022_rename_ccy_error_payment_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='price.cryptoprice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='price_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='price.cryptoprice'),
            preserve_default=False,
        ),
    ]
