# Generated by Django 4.0.3 on 2022-10-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_rename_problem_payment_is_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='vendor_url',
            field=models.URLField(default='http://localhost:8888', max_length=255),
            preserve_default=False,
        ),
    ]
