# Generated by Django 4.0.3 on 2022-11-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_vendorpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('throttle_rate', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
