# Generated by Django 4.0.3 on 2022-11-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='VendorPayment',
        ),
    ]
