# Generated by Django 4.0.3 on 2022-10-31 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment.hmac_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HMACKey',
            fields=[
                ('key', models.CharField(default=payment.hmac_auth.models.HMACKey.generate_key, max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('secret', models.CharField(default=payment.hmac_auth.models.HMACKey.generate_key, max_length=40, verbose_name='Secret')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hmac_key', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
