# Generated by Django 4.0.3 on 2022-11-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmac_auth', '0002_rename_user_hmackey_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmackey',
            name='wallet_name',
            field=models.CharField(default='leaf-wallet', max_length=255),
            preserve_default=False,
        ),
    ]
