# Generated by Django 4.0.3 on 2022-11-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmac_auth', '0003_hmackey_wallet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmackey',
            name='wallet_name',
        ),
    ]
